name: JRuby and JRuby-head

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Test JRuby and JRuby-head
    steps:
    - name: Install libraries
      run: sudo apt install haveged
    - uses: actions/checkout@v2
    - name: Set up RVM
      run: |
        curl -sSL https://get.rvm.io | bash
    - name: Set up jruby
      run: |
        source $HOME/.rvm/scripts/rvm
        rvm install jruby
        rvm --default use jruby
    - name: Set up jruby-head
      run: |
        source $HOME/.rvm/scripts/rvm
        rvm use system
        rvm install jruby-head
        tail -100 /home/runner/.rvm/log/1743161614_jruby-head/mvnw.log
        rvm --default use jruby-head
    - name: Install dependencies
      run: |
        source $HOME/.rvm/scripts/rvm
        gem install bundler --no-document
        bundle install
    - name: Run test
      run: |
        source $HOME/.rvm/scripts/rvm
        rake test
